# Generated by Django 4.1.1 on 2023-04-19 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('students', models.ManyToManyField(blank=True, related_name='classs', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAtClass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=None)),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None)),
                ('duration', models.IntegerField(blank=True, default=60, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.class')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('SingleMCQ', 'SingleMCQ'), ('MultipleMCQ', 'MultipleMCQ'), ('TrueFalse', 'TrueFalse'), ('Subjective', 'Subjective')], max_length=100)),
                ('mark', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam')),
                ('options', models.ManyToManyField(blank=True, related_name='questions', to='exam.option')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('STARTED', 'STARTED'), ('SUBMITTED', 'SUBMITTED')], default='NOT_STARTED', max_length=100)),
                ('mark', models.IntegerField(blank=True, default=0, null=True)),
                ('total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('percentage', models.IntegerField(blank=True, default=0, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('mark', models.IntegerField(default=1)),
                ('answered', models.BooleanField(default=False)),
                ('answersheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.answersheet')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question')),
            ],
        ),
    ]
